version: '3'
services:
  web:
    image: nginx:latest
    container_name: petra-url-shortener
    ports:
      - "8080:80"
    volumes:
      - .:/usr/share/nginx/html:ro 
    restart: unless-stopped
